import React, { useState, useEffect } from 'react';
import Modal from './Modal';
import Button from './Button';
import apiClient from '../../api/apiClient';
import toast from 'react-hot-toast';

const TotpSetupModal = ({ onClose, onSuccess }) => {
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [setupData, setSetupData] = useState(null);
  const [code, setCode] = useState('');

  useEffect(() => {
    const fetchSetupData = async () => {
      try {
        const res = await apiClient.post('/auth/admin/totp/setup');
        setSetupData(res.data.data);
      } catch (err) {
        toast.error('Failed to initiate 2FA setup');
        onClose();
      } finally {
        setLoading(false);
      }
    };
    fetchSetupData();
  }, [onClose]);

  const handleVerify = async (e) => {
    e.preventDefault();
    setVerifying(true);
    try {
      await apiClient.post('/auth/admin/totp/enable', { code });
      toast.success('Two-Factor Authentication enabled successfully!');
      onSuccess();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Invalid code');
      setVerifying(false);
    }
  };

  return (
    <Modal title="Set Up Two-Factor Authentication" onClose={onClose}>
      <div className="p-4 space-y-4">
        {loading ? (
          <div className="flex flex-col items-center justify-center space-y-4 py-8">
            <div className="w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
            <p className="text-sm text-gray-500">Generating secure QR code...</p>
          </div>
        ) : (
          <>
            <p className="text-sm text-gray-600 mb-4">
              1. Install an authenticator app (like Google Authenticator or Authy) on your phone.
            </p>
            <p className="text-sm text-gray-600 mb-4">
              2. Scan the QR code below:
            </p>
            <div className="flex justify-center bg-white p-4 rounded-xl border border-gray-100">
              {setupData?.qrCode && (
                <img src={setupData.qrCode} alt="TOTP QR Code" className="w-48 h-48" />
              )}
            </div>
            
            <p className="text-sm text-center text-gray-500 mt-2">
              Or enter this code manually: <br />
              <span className="font-mono font-bold text-gray-800 tracking-wider bg-gray-100 px-2 py-1 rounded">{setupData?.secret}</span>
            </p>

            <form onSubmit={handleVerify} className="mt-6 space-y-4">
              <p className="text-sm text-gray-600 mb-2">
                3. Enter the 6-digit code generated by the app to verify:
              </p>
              <input
                type="text"
                placeholder="000000"
                value={code}
                onChange={(e) => setCode(e.target.value)}
                maxLength={6}
                required
                className="w-full text-center tracking-widest text-lg px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
              />
              <div className="flex justify-end gap-3 pt-4">
                <Button variant="secondary" onClick={onClose} type="button">Cancel</Button>
                <Button type="submit" disabled={verifying || code.length < 6}>
                  {verifying ? 'Verifying...' : 'Verify & Enable'}
                </Button>
              </div>
            </form>
          </>
        )}
      </div>
    </Modal>
  );
};

export default TotpSetupModal;
